### ISSUE TITLE
Calculation result must be rounded

### ISSUE THREAD

**Issue by takrim1999** [35-hasib/web_development_project#2]
The calculation result is overflowing the screen, and there is no button to move the cursor. so the result should be rounded up to a point

**Comment by 35-hasib** [comment]
The calculator i created so long ago.  Thank you for pointing this out. To improve usability, I'll ensure that results are rounded appropriately to fit the screen and consider adding navigation options for better interaction with the displayed output.

**Comment by takrim1999** [comment]
Thanks.
Created A pull request and tried to fix the issue. You can merge it if you
want
